class Strings {
  static const connectWith = 'CONNECT WITH';
  static const home = 'HOME';
  static const signOut = 'SIGN OUT';
  static const places = 'MAP VIEW';
  static const restaurants = 'EAT & DRINK';
  static const stayAndPlay = 'STAY & PLAY';
  static const accommodation = 'ACCOMODATION';
  static const events = "WHAT'S HAPPENING";
  static const listView = 'LIST VIEW';
  static const mapView = 'MAP VIEW';
  static const cruises ='BOATS & CHARTERS';
  static const transport = 'TRANSPORT & PARKING';
  static const settings = 'SETTINGS';
  static const locationSettings = 'LOCATION SETTINGS';
  static const notificationSettings = 'NOTIFICATION SETTINGS';
  static const contactUs = 'ABOUT VIADUCT';
  static const emergencyPhone = 'EMERGENCY PHONE';
  static const emergencyPhoneValue = '(09) 872 1233';
  static const email = 'EMAIL';
  static const emailValue = 'admin@brightnights.co.nz';
  static const bookABerth = 'BOOK A BERTH';
  static const marina = 'MARINA';
  static const contractors = 'CONTRACTORS';
  static const marinaMap = 'MARINA MAP';
  static const contractorsAndServices = 'CONTRACTORS & SERVICES';
  static const gettingHere = 'GETTING HERE';
  static const aboutViaduct = "Viaduct Harbour is a vibrant community situated in and around Auckland’s waterfront. With the continued development of residential apartments, it’s the place of choice for those wanting to live in the heart of the Supercity. Viaduct Harbour has a vibrant hospitality scene and is the hot spot for unforgettable dining experiences. And with world-class hotels and accommodation, it’s fast becoming on par with other harbour-based cities around the world as a destination of choice.";
}
